### ISSUE TITLE
Error in workflow 'Calendar'

### ISSUE THREAD

**Issue by Ronniexia** [cleobis/alfred-cal#5]
![image](https://user-images.githubusercontent.com/35653430/196025691-b359c2ba-634b-4126-83e4-e3007a606c50.png)

**Comment by cleobis** [comment]
Please open the workflow in the Alfred preferences and click the bug symbol. Run the workflow again. Send any messages that appear in the console. 

https://www.alfredapp.com/help/workflows/advanced/debugger/

**Comment by Ronniexia** [comment]
> Please open the workflow in the Alfred preferences and click the bug symbol. Run the workflow again. Send any messages that appear in the console. https://www.alfredapp.com/help/workflows/advanced/debugger/
========================================================================================

Thank you for replying to my message😂. 
Sorry about my poor English. According to your advice, I reported the following error:

========================================================================================
![image](https://user-images.githubusercontent.com/35653430/196048382-cd4e74ac-164b-4a36-80de-982ce13ff3bb.png)

========================================================================================
[00:57:27.531] ERROR: Calendar[Script Filter] Code 1: .
00:57:27 workflow.py:2093 DEBUG    ---------- Calendar (1.6.3) ----------
00:57:27 workflow.py:1483 DEBUG    reading settings from /Users/xiachao/Library/Application Support/Alfred/Workflow Data/zmin.calendar/settings.json
00:57:27 workflow.py:2394 INFO     checking for update ...
00:57:27 background.py:233 DEBUG    [__workflow_update_check] command cached: /Users/xiachao/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/zmin.calendar/__workflow_update_check.argcache
00:57:27 background.py:237 DEBUG    [__workflow_update_check] passing job to background runner: ['/Library/Developer/CommandLineTools/usr/bin/python3', '-m', 'workflow.background', '__workflow_update_check']
.
00:57:27 workflow.py:2093 DEBUG    ---------- Calendar (1.6.3) ----------
00:57:27 background.py:243 DEBUG    [__workflow_update_check] background job started
00:57:27 format.py:92 INFO     Font: OPPOSans Light 18pt
00:57:27 workflow.py:2114 ERROR    Command '['osascript', './textWidth.scpt', 'OPPOSans Light', '18', '    Su        Mo        Tu        We        Th        Fr        Sa    ', '[["", "", "", "", "", "", "1"], ["2", "3", "4", "5", "6", "7", "8"], ["9", "10", "11", "12", "13", "14", "15"], ["16", "\\u2605", "18", "19", "20", "21", "22"], ["23", "24", "25", "26", "27", "28", "29"], ["30", "31", "", "", "", "", ""]]']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/Users/xiachao/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.891F88B1-9C3E-4BEB-BB9D-BCAEFCB16B13/workflow/workflow.py", line 2107, in run
    func(self)
  File "/Users/xiachao/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.891F88B1-9C3E-4BEB-BB9D-BCAEFCB16B13/main.py", line 41, in main
    texts = cal.get_weeks_text(year, month, self.first_day)
  File "/Users/xiachao/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.891F88B1-9C3E-4BEB-BB9D-BCAEFCB16B13/cal.py", line 31, in get_weeks_text
    texts += format.format(self.get_cal(self.get_weeks(year, month, first_weekday)), texts[-1])
  File "/Users/xiachao/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.891F88B1-9C3E-4BEB-BB9D-BCAEFCB16B13/format.py", line 174, in format
    return self.formatApp(weeks, title)
  File "/Users/xiachao/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.891F88B1-9C3E-4BEB-BB9D-BCAEFCB16B13/format.py", line 191, in formatApp
    status = subprocess.run(["osascript", "./textWidth.scpt", self.font[0], str(self.font[1]), title, json.dumps(weeks)],
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['osascript', './textWidth.scpt', 'OPPOSans Light', '18', '    Su        Mo        Tu        We        Th        Fr        Sa    ', '[["", "", "", "", "", "", "1"], ["2", "3", "4", "5", "6", "7", "8"], ["9", "10", "11", "12", "13", "14", "15"], ["16", "\\u2605", "18", "19", "20", "21", "22"], ["23", "24", "25", "26", "27", "28", "29"], ["30", "31", "", "", "", "", ""]]']' returned non-zero exit status 1.
00:57:27 workflow.py:2136 DEBUG    ---------- finished in 0.253s ----------

**Comment by Ronniexia** [comment]
Another amazing thing is that when the macos is in dark mode, this is fine. 
However, in non-dark mode, the above problem occurs.

<img width="818" alt="image" src="https://user-images.githubusercontent.com/35653430/196048537-d1824442-508f-4dff-933b-d8088ac0869d.png">

<img width="671" alt="image" src="https://user-images.githubusercontent.com/35653430/196048516-eeead585-450d-4dca-8a35-af01eb9888c3.png">

**Comment by Ronniexia** [comment]
I just tried changing alfred's other appearances and found that wide Windows are fine, while narrow Windows cause errors. I guess it has something to do with the width of the window of alfred?

**Comment by cleobis** [comment]
I suspect it is something with the "OPPOSans Light” font used with the themes that are having the issue, not the width.

Attached is a version of the calculation that appears. Could you unzip it, open it in the Script Editor application that is included with macOS. From the View menu, choose Show Log. Run the script. Report what is displayed. I expect it will display Font is missing light shown in the image below.

Do you have a link for where you got the OPPOSans Light font. It appears to not be standard with macOS.

Sample image: https://user-images.githubusercontent.com/26043198/196068062-c14c3906-2000-4bdc-8186-7f6c98695ef0.png
[textWidth.scpt.zip](https://github.com/cleobis/alfred-cal/files/9796092/textWidth.scpt.zip)

**Comment by cleobis** [comment]
Unless I receive more information on the font, I will consider this resolved.

**Comment by cleobis** [comment]
No further information was received.

**Comment by Ronniexia** [comment]
> No further information was received.没有收到进一步的资料。

Sorry, my computer had a problem last time, and during the COVID-19 outbreak in the new building, there were changes in my job. After a lot of things, I forgot to reply to your email. I am truly sorry.

**Comment by Ronniexia** [comment]
> I suspect it is something with the "OPPOSans Light” font used with the themes that are having the issue, not the width.
> 
> Attached is a version of the calculation that appears. Could you unzip it, open it in the Script Editor application that is included with macOS. From the View menu, choose Show Log. Run the script. Report what is displayed. I expect it will display Font is missing light shown in the image below.
> 
> Do you have a link for where you got the OPPOSans Light font. It appears to not be standard with macOS.
> 
> Sample image: https://user-images.githubusercontent.com/26043198/196068062-c14c3906-2000-4bdc-8186-7f6c98695ef0.png
> [textWidth.scpt.zip](https://github.com/cleobis/alfred-cal/files/9796092/textWidth.scpt.zip)

Yes, as you said, it is displaying missing fonts，like this：

<img width="1400" height="1460" alt="Image" src="https://github.com/user-attachments/assets/3345c78a-d901-41fd-9d57-89c96bde8ecb" />
==============================================

I followed your advice and checked the font configuration for different themes. As expected, I found that the font configuration for the daytime and nighttime modes was different. After changing everything to system fonts, this problem was perfectly solved! Thank you for your guidance!

1. Night mode, all system fonts, so there is no problem
<img width="1175" height="762" alt="Image" src="https://github.com/user-attachments/assets/0fcb2bb0-5a3b-4231-b21c-70acaea4b77f" />

2. Daytime mode, with annoying OPPO Sans font, so there will be errors.



==============================================

Thank you very much for taking the time to help me locate the problem and providing excellent analytical ideas. Thank you again! And you, my friend, are the true hero!
